import {
  LayoutDashboard, Package, Warehouse, ClipboardCheck, FileInput, FileOutput,
  Search, AlertTriangle, History, BarChart3, Users, Shield,
  DatabaseBackup, FolderTree, ClipboardList, MapPin, Boxes, ListChecks,
  CardSim,
  Container,
  Building,
  User2,
  User2Icon,
  User, RefreshCw, Truck, CreditCard, UserCheck, UserX, UserPlus, UserMinus,ShieldCheck,FileCheck
} from "lucide-react";

export const menuByRole = {
  NhanVien: [
    { label: "Tổng quan", path: "/staff", icon: LayoutDashboard },
    { section: "Quản lý hàng hóa" },
    { label: "Sản phẩm", path: "/products", icon: Package },
    { label: "Danh mục sản phẩm", path: "/categories", icon: FolderTree },
    { label: "Kho", path: "/Kho", icon: MapPin },
    { label: "Tồn kho", path: "/inventory", icon: Warehouse },
    { section: "Giao dịch kho" },
    { label: "Phiếu nhập", path: "/imports", icon: FileInput },
    { label: "Phiếu xuất", path: "/exports", icon: FileOutput },
    { label: "Phiếu bảo hành", path: "/PhieuBaoHanh", icon: ShieldCheck },
    { section: "Báo cáo" },
    { label: "Báo cáo tồn kho", path: "/reports", icon: BarChart3 },
  ],
  QuanLy: [
    { label: "Tổng quan", path: "/manager", icon: LayoutDashboard },
    { section: "Quản lý hàng hóa" },
    { label: "Sản phẩm", path: "/products", icon: Package },
    { label: "Danh mục sản phẩm", path: "/categories", icon: FolderTree },
    { label: "Kho", path: "/Kho", icon: MapPin },
    { label: "Tồn kho", path: "/inventory", icon: Warehouse },
    { section: "Giao dịch kho" },
    { label: "Phiếu nhập", path: "/imports", icon: FileInput },
    { label: "Phiếu xuất", path: "/exports", icon: FileOutput },
    { label: "Phê duyệt", path: "/approvals", icon: ClipboardCheck },
    { label: "Phiếu bảo hành", path: "/PhieuBaoHanh", icon: FileCheck },
    { section: "Báo cáo & Giám sát" },
    { label: "Báo cáo tồn kho", path: "/reports", icon: BarChart3 },
    { section: "Hệ thống & Đối tác" },
    { label: "Nhân viên", path: "/users", icon: Users },
    { label: "Nhà Cung cấp", path: "/NCC", icon: Building },
    { label: "Khách Hàng", path: "/customers", icon: Users },
  ],
  Admin: [
    { label: "Tổng quan", path: "/admin", icon: LayoutDashboard },
    { section: "Quản lý tài khoản" },
    { label: "Người dùng", path: "/users", icon: Users },
    { label: "Tài Khoản", path: "/tk", icon: User2Icon },
    { label: "Vai trò & phân quyền", path: "/roles", icon: Shield },
    { label: "Trang cá nhân", path: "/profile", icon: User2 },
    { section: "Hàng hóa" },
    { label: "Sản phẩm", path: "/products", icon: Package },
    { label: "Danh mục sản phẩm", path: "/categories", icon: FolderTree },
    { label: "Lịch sử hệ thống", path: "/logs", icon: History },
  ],
};
