import {
  LayoutDashboard, Package, Warehouse, ClipboardCheck, FileInput, FileOutput,
  Search, AlertTriangle, History, BarChart3, Users, Shield,
  DatabaseBackup, FolderTree, ClipboardList, MapPin, Boxes, ListChecks,
  CardSim,
  Container,
  Building,
  User2,
  User2Icon,
  User, RefreshCw, Truck, CreditCard, UserCheck, UserX, UserPlus, UserMinus,ShieldCheck
} from "lucide-react";

export const menuByRole = {
  NhanVien: [
    { label: "Tổng quan", path: "/staff", icon: LayoutDashboard },
    { section: "Hàng hóa" },
    { label: "Danh mục", path: "/categories", icon: FolderTree },
    { label: "Sản phẩm", path: "/products", icon: Package },
    { label: "Kho", path: "/Kho", icon: MapPin },
    { label: "Tồn kho", path: "/inventory", icon: Warehouse },
    { section: "Nhập - xuất" },
    { label: "Phiếu nhập", path: "/imports", icon: FileInput },
    { label: "Phiếu xuất", path: "/exports", icon: FileOutput },
    { label: "Bảo hành sản phẩm", path: "/baohanh", icon: ShieldCheck },
    { label: "Phieu bảo hành", path: "/PhieuBaoHanh", icon: ShieldCheck },
    { section: "Xử lý vấn đề" },
    { label: "Báo cáo tồn kho", path: "/reports", icon: BarChart3 },
  ],
  QuanLy: [
    { label: "Tổng quan", path: "/manager", icon: LayoutDashboard },
    { section: "Tồn kho" },
    { label: "Theo dõi tồn kho", path: "/inventory", icon: Warehouse },
    { label: "Sản phẩm", path: "/products", icon: Package },
    { label: "Kho", path: "/Kho", icon: MapPin },
    { label: "Danh mục sản phẩm", path: "/categories", icon: FolderTree },

    { section: "Giao dịch" },
    { label: "Phiếu nhập", path: "/imports", icon: FileInput },
    { label: "Phiếu xuất", path: "/exports", icon: FileOutput },
    { label: "Phê duyệt", path: "/approvals", icon: ClipboardCheck },
    { label: "Bảo hành sản phẩm", path: "/baohanh", icon: ShieldCheck },
    { label: "Phieu bảo hành", path: "/PhieuBaoHanh", icon: ShieldCheck },

    { section: "Báo cáo" },
    { label: "Báo cáo tồn kho", path: "/reports", icon: BarChart3 },
    { label: "Báo cáo sự cố", path: "/incidents", icon: AlertTriangle },
    { section: "Quản lý" },
    { label: "Nhân viên", path: "/users", icon: Users },
    { label: "Nhà Cung cấp", path: "/NCC", icon: Building },
    { label: "Khách Hàng", path: "/customers", icon: Users },
    { section: "Lịch sử" },
    { label: "Lịch sử hoạt động", path: "/logs", icon: History },
  ],
  Admin: [
    { label: "Tổng quan", path: "/admin", icon: LayoutDashboard },
    { section: "Quản lý người dùng" },
    { label: "Người dùng", path: "/users", icon: Users },
    { label: "Vai trò & phân quyền", path: "/roles", icon: Shield },
    { label: "Trang cá nhân", path: "/profile", icon: User2 },
    { section: "Quản lý sản phẩm" },
    { label: "Sản phẩm", path: "/products", icon: Package },
    { label: "Danh mục sản phẩm", path: "/categories", icon: FolderTree },
    { section: "Giám sát hệ thống" },
    { label: "Lịch sử hoạt động", path: "/logs", icon: History },
    { section: "Quản lý tài khoản và phân quyền" },
    { label: "Tài Khoản", path: "/tk", icon: User2Icon },
  ],
};
